<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sursoft</groupId>
        <artifactId>vision-defect-traceability</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>vision-defect-framework</artifactId>
    <name>vision-defect-framework</name>
    <description>安全、JWT、CORS、切面等基础设施</description>
    <dependencies>
        <dependency>
            <groupId>com.sursoft</groupId>
            <artifactId>vision-defect-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sursoft</groupId>
            <artifactId>vision-defect-system</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
        </dependency>
    </dependencies>
</project>
